# -*- coding: utf-8 -*-
"""Retraction_Watch_Pastel_Enhanced_Analysis_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17AE71I7XY2dxN-7a0jGZ0YLE_m9FSVu7

# Retraction Watch Data Analysis Project
"""

# Cell 1— Imports and Configuration

from pathlib import Path
from itertools import combinations
from collections import Counter
import shutil
import warnings
import re

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
try:
    from scipy import stats

    from scipy.stats import norm, fisher_exact
except ModuleNotFoundError:
    import subprocess
    import sys
    print("SciPy not found. Installing scipy...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "scipy"])
    from scipy import stats
    from scipy.stats import norm, fisher_exact
from scipy.stats import norm, fisher_exact
try:
    import networkx as nx
except ModuleNotFoundError:
    import subprocess
    import sys
    print("networkx not found. Installing networkx...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "networkx"])
    import networkx as nx
import hashlib
import math

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 50)
pd.set_option("display.max_colwidth", 120)

# Cell 2-Load Data and Configuration
DATA_PATH = None
ALLOW_WEB_FALLBACK = True
GITLAB_RAW_URL = "https://gitlab.com/crossref/retraction-watch-data/-/raw/main/retraction_watch.csv"

OUTPUT_DIR = Path("retraction_watch_outputs")
PLOTS_DIR = OUTPUT_DIR / "plots"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
PLOTS_DIR.mkdir(parents=True, exist_ok=True)

#Helper Functions

def locate_dataset(explicit_path=None):
    """Find the dataset in local, Colab, Kaggle, or ChatGPT-style paths."""
    candidates = []
    if explicit_path:
        candidates.append(Path(explicit_path))

    candidates.extend([
        Path("retraction_watch.csv"),
        Path("/content/retraction_watch.csv"),
        Path("/mnt/data/retraction_watch.csv"),
    ])

    kaggle_root = Path("/kaggle/input")
    if kaggle_root.exists():
        candidates.extend(kaggle_root.rglob("retraction_watch.csv"))

    for candidate in candidates:
        try:
            if candidate.exists() and candidate.is_file():
                return candidate
        except OSError:
            pass
    return None

def save_and_show(fig, filename):
    """Save each figure as PNG and display it in the notebook."""
    out = PLOTS_DIR / filename
    fig.tight_layout()
    fig.savefig(out, dpi=180, bbox_inches="tight")
    plt.show()
    plt.close(fig)
    print(f"Saved: {out}")

def explode_semicolon(series):
    """Explode semicolon-delimited multi-value fields into clean individual values."""
    return (
        series.dropna()
        .astype(str)
        .str.split(";")
        .explode()
        .str.strip()
        .replace("", pd.NA)
        .dropna()
    )

def count_semicolon_items(value):
    """Count non-empty semicolon-delimited items."""
    if pd.isna(value):
        return 0
    return sum(bool(x.strip()) for x in str(value).split(";"))

def clean_subject_label(value):
    """Remove Retraction Watch subject code prefixes such as (B/T) or (SOC)."""
    return re.sub(r"^\([^)]+\)\s*", "", str(value)).strip()

def annotate_barh(ax, values):
    """Add compact value labels to horizontal bars."""
    for i, v in enumerate(values):
        ax.text(v, i, f" {int(v):,}", va="center", fontsize=8)

def pct(x):
    return f"{100*x:.1f}%"

# ---------- Solid pastel academic visualization theme ----------
from cycler import cycler
from matplotlib.colors import LinearSegmentedColormap
PASTEL_PALETTE = [
    "#7EB0D5",  # pastel blue
    "#76D7C4",  # pastel teal
    "#AF7AC5",  # pastel lavender
    "#F1948A",  # pastel coral
    "#F7DC6F",  # pastel gold
    "#82E0AA",  # pastel mint
    "#F5B7B1",  # pastel rose
    "#85C1E9",  # pastel periwinkle
]
plt.rcParams.update({
    "axes.prop_cycle": cycler(color=PASTEL_PALETTE),
    "axes.facecolor": "#FCFDFF",
    "figure.facecolor": "white",
    "axes.grid": True,
    "grid.alpha": 0.16,
    "grid.linestyle": "--",
    "axes.titleweight": "bold",
})
PASTEL_BLUE_CMAP = LinearSegmentedColormap.from_list(
    "pastel_blue", ["#F7FBFF", "#D6EAF8", "#AED6F1", "#7FB3D5", "#5499C7"]
)
PASTEL_DIVERGING = LinearSegmentedColormap.from_list(
    "pastel_diverging", ["#A9CCE3", "#EAF2F8", "#FFFFFF", "#FDEDEC", "#F5B7B1"]
)

# Cell 3 — Load the Dataset

source_path = locate_dataset(DATA_PATH)

if source_path is not None:
    print(f"Loading local dataset: {source_path}")
    raw_df = pd.read_csv(source_path, low_memory=False)
else:
    if not ALLOW_WEB_FALLBACK:
        raise FileNotFoundError(
            "retraction_watch.csv not found. Upload it to Colab/Kaggle or set DATA_PATH."
        )
    print("Local file not found. Loading the current CSV from the official GitLab raw URL...")
    try:
        raw_df = pd.read_csv(GITLAB_RAW_URL, low_memory=False)
    except Exception as exc:
        raise RuntimeError(
            "Could not load from GitLab. Upload retraction_watch.csv manually and set DATA_PATH."
        ) from exc

print(f"Loaded shape: {raw_df.shape[0]:,} rows × {raw_df.shape[1]} columns")

# Cell 4 — Schema, Data Types, and Memory

print("Column names:")
print(raw_df.columns.tolist())
print("\nData types:")
display(raw_df.dtypes.to_frame("dtype"))
print("\nDataFrame info:")
raw_df.info()

# Cell 4 — Preview the First Rows

raw_df.head()

# Cell 5 — Preview the Last Rows

raw_df.tail()

# Cell 5 — Initial Data Quality Audit

audit_before = pd.DataFrame({
    "missing_count": raw_df.isna().sum(),
    "missing_pct": (raw_df.isna().mean() * 100).round(2),
    "unique_non_null": raw_df.nunique(dropna=True)
}).sort_values("missing_pct", ascending=False)

print(f"Exact duplicate rows: {raw_df.duplicated().sum():,}")
print(f"Completely empty rows: {raw_df.isna().all(axis=1).sum():,}")
if "Record ID" in raw_df.columns:
    print(f"Duplicate Record IDs (including repeated missing IDs): {raw_df['Record ID'].duplicated().sum():,}")

display(audit_before)

df = raw_df.copy()

exact_duplicates_before = int(df.duplicated().sum())
record_id_duplicates_before = int(df["Record ID"].duplicated().sum())

# Exact duplicates are safe to remove.
df = df.drop_duplicates().copy()

# Record ID is the database's internal identifier. If duplicates remain,
# retain the first occurrence after reporting them.
if df["Record ID"].duplicated().any():
    duplicated_ids = df.loc[df["Record ID"].duplicated(keep=False), "Record ID"].dropna().unique()
    print(f"Warning: {len(duplicated_ids):,} duplicated Record IDs remain.")
    df = df.drop_duplicates(subset=["Record ID"], keep="first").copy()

print(f"Exact duplicates before removal: {exact_duplicates_before:,}")
print(f"Duplicate Record IDs before removal: {record_id_duplicates_before:,}")
print(f"Final record count after deduplication: {len(df):,}")
print(f"Record ID unique now: {df['Record ID'].is_unique}")

# Cell 7 — Clean Empty Rows, Empty Columns, and Strings

df = raw_df.copy()

rows_before = len(df)
df = df.dropna(how="all").copy()
blank_rows_removed = rows_before - len(df)

empty_columns = [c for c in df.columns if df[c].isna().all()]
df = df.drop(columns=empty_columns)

object_cols = df.select_dtypes(include="object").columns
for col in object_cols:
    df[col] = df[col].astype("string").str.strip()
    df[col] = df[col].replace({"": pd.NA})

print(f"Blank rows removed: {blank_rows_removed:,}")
print(f"Fully empty columns removed: {empty_columns}")
print(f"Shape after structural cleaning: {df.shape}")

# Cell 8 — Normalize Missing Identifier Values and Numeric IDs

identifier_cols = [
    "RetractionDOI", "OriginalPaperDOI", "URLS"
]
missing_tokens = {
    "Unavailable": pd.NA, "unavailable": pd.NA, "UNAVAILABLE": pd.NA,
    "N/A": pd.NA, "n/a": pd.NA, "NA": pd.NA, "None": pd.NA,
    "null": pd.NA, "NULL": pd.NA
}

for col in identifier_cols:
    if col in df.columns:
        df[col] = df[col].replace(missing_tokens)

for col in ["Record ID", "RetractionPubMedID", "OriginalPaperPubMedID"]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

# Retraction Watch uses 0 to mean PubMed ID unavailable.
for col in ["RetractionPubMedID", "OriginalPaperPubMedID"]:
    if col in df.columns:
        df.loc[df[col] == 0, col] = pd.NA

display(df[["Record ID", "RetractionDOI", "OriginalPaperDOI",
            "RetractionPubMedID", "OriginalPaperPubMedID"]].head())

# Cell 9 — Parse Dates and Validate Chronology

for col in ["RetractionDate", "OriginalPaperDate"]:
    df[col] = pd.to_datetime(df[col], errors="coerce")

date_quality = pd.DataFrame({
    "min_date": [df["RetractionDate"].min(), df["OriginalPaperDate"].min()],
    "max_date": [df["RetractionDate"].max(), df["OriginalPaperDate"].max()],
    "missing_or_unparsed": [df["RetractionDate"].isna().sum(), df["OriginalPaperDate"].isna().sum()]
}, index=["RetractionDate", "OriginalPaperDate"])

display(date_quality)

negative_date_order = (df["RetractionDate"] < df["OriginalPaperDate"]).sum()
print(f"Rows with retraction/update date earlier than original publication date: {negative_date_order:,}")

# Cell 10 — Feature Engineering

df["RetractionYear"] = df["RetractionDate"].dt.year.astype("Int64")
df["RetractionMonth"] = df["RetractionDate"].dt.to_period("M").astype("string")
df["OriginalYear"] = df["OriginalPaperDate"].dt.year.astype("Int64")

df["LagDays"] = (df["RetractionDate"] - df["OriginalPaperDate"]).dt.days
df.loc[df["LagDays"] < 0, "LagDays"] = np.nan
df["LagYears"] = df["LagDays"] / 365.25

for source_col, new_col in [
    ("Author", "AuthorCount"),
    ("Country", "CountryCount"),
    ("Subject", "SubjectCount"),
    ("Reason", "ReasonCount"),
    ("ArticleType", "ArticleTypeCount"),
]:
    df[new_col] = df[source_col].apply(count_semicolon_items)

df["InternationalCollaboration"] = np.where(
    df["CountryCount"] > 1, "Multiple countries", "Single/unknown country"
)

df["HasOriginalDOI"] = df["OriginalPaperDOI"].notna()
df["HasRetractionDOI"] = df["RetractionDOI"].notna()
df["HasURL"] = df["URLS"].notna()

# Periods useful for comparing reason composition over time.
df["RetractionPeriod"] = pd.cut(
    df["RetractionYear"].astype(float),
    bins=[-np.inf, 2009, 2014, 2019, 2024, np.inf],
    labels=["≤2009", "2010–2014", "2015–2019", "2020–2024", "2025+"]
)

display(df[[
    "Record ID", "RetractionDate", "OriginalPaperDate", "LagYears",
    "AuthorCount", "CountryCount", "ReasonCount", "RetractionNature"
]].head())

# Cell 11 — Post-Cleaning Quality Summary

audit_after = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_pct": (df.isna().mean() * 100).round(2),
    "unique_non_null": df.nunique(dropna=True)
}).sort_values("missing_pct", ascending=False)

quality_summary = pd.DataFrame({
    "Metric": [
        "Raw rows",
        "Valid cleaned rows",
        "Blank rows removed",
        "Raw columns",
        "Cleaned columns",
        "Exact duplicate rows remaining",
        "Duplicate Record IDs remaining",
        "Retraction date parse failures",
        "Original publication date parse failures"
    ],
    "Value": [
        len(raw_df),
        len(df),
        blank_rows_removed,
        raw_df.shape[1],
        df.shape[1],
        int(df.duplicated().sum()),
        int(df["Record ID"].duplicated().sum()),
        int(df["RetractionDate"].isna().sum()),
        int(df["OriginalPaperDate"].isna().sum())
    ]
})

display(quality_summary)
display(audit_after.head(12))

# Cell 12 — Build Long-Format Tables for Multi-Value Fields

country_long = explode_semicolon(df["Country"])
subject_long = explode_semicolon(df["Subject"]).map(clean_subject_label)
reason_long = explode_semicolon(df["Reason"])
article_type_long = explode_semicolon(df["ArticleType"])

country_counts = country_long.value_counts()
subject_counts = subject_long.value_counts()
reason_counts = reason_long.value_counts()
article_type_counts = article_type_long.value_counts()

print(f"Unique country labels: {country_long.nunique():,}")
print(f"Unique subject labels: {subject_long.nunique():,}")
print(f"Unique reason labels: {reason_long.nunique():,}")
print(f"Unique article-type labels: {article_type_long.nunique():,}")

# Cell 13 — Plot Notice / Update Nature

nature_counts = df["RetractionNature"].fillna("Unknown").value_counts().sort_values()

fig, ax = plt.subplots(figsize=(9, 5))
ax.barh(nature_counts.index, nature_counts.values, color=PASTEL_PALETTE[7], edgecolor="white", linewidth=0.6)
ax.set_title("Retraction Watch Records by Notice Nature")
ax.set_xlabel("Number of records")
ax.set_ylabel("Notice nature")
annotate_barh(ax, nature_counts.values)
save_and_show(fig, "02_notice_nature_counts.png")

# Cell 14 — Plot Annual Record Trend

annual_counts = df.dropna(subset=["RetractionYear"]).groupby("RetractionYear").size()
annual_counts = annual_counts[annual_counts.index >= 2000]

fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(annual_counts.index.astype(int), annual_counts.values, marker="o", markersize=4, linewidth=2.2, color=PASTEL_PALETTE[0])
ax.set_title("Annual Retraction Watch Records Since 2000")
ax.set_xlabel("Year")
ax.set_ylabel("Number of records")
ax.grid(axis="y", alpha=0.25)
save_and_show(fig, "03_annual_records_since_2000.png")

# Cell 15 — Plot Annual Trend by Notice Nature

annual_nature = (
    df.dropna(subset=["RetractionYear", "RetractionNature"])
      .query("RetractionYear >= 2000")
      .groupby(["RetractionYear", "RetractionNature"])
      .size()
      .unstack(fill_value=0)
)

fig, ax = plt.subplots(figsize=(12, 6))
for col in annual_nature.columns:
    ax.plot(annual_nature.index.astype(int), annual_nature[col], marker="o", markersize=2, label=col)
ax.set_title("Annual Records by Notice Nature Since 2000")
ax.set_xlabel("Year")
ax.set_ylabel("Number of records")
ax.legend()
ax.grid(axis="y", alpha=0.25)
save_and_show(fig, "04_annual_records_by_nature.png")

# Cell 16 — Plot Recent Monthly Trend

max_date = df["RetractionDate"].max()
recent_start = max_date - pd.DateOffset(years=5)
recent = df.loc[df["RetractionDate"].between(recent_start, max_date)].copy()
monthly = recent.set_index("RetractionDate").resample("MS").size()

fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(monthly.index, monthly.values, linewidth=2.2, color=PASTEL_PALETTE[2])
ax.set_title(f"Monthly Retraction Watch Records — Last 5 Years Through {max_date.date()}")
ax.set_xlabel("Month")
ax.set_ylabel("Number of records")
ax.grid(axis="y", alpha=0.25)
save_and_show(fig, "05_recent_monthly_trend.png")

# Cell 17 — Plot Top Publishers

top_publishers = df["Publisher"].fillna("Unknown").value_counts().head(20).sort_values()

fig, ax = plt.subplots(figsize=(11, 8))
ax.barh(top_publishers.index, top_publishers.values, color=PASTEL_PALETTE[2], edgecolor="white", linewidth=0.6)
ax.set_title("Top 20 Publishers by Number of Retraction Watch Records")
ax.set_xlabel("Number of records")
ax.set_ylabel("Publisher")
annotate_barh(ax, top_publishers.values)
save_and_show(fig, "06_top_publishers.png")

# Cell 18 — Plot Top Journals

top_journals = df["Journal"].fillna("Unknown").value_counts().head(20).sort_values()

fig, ax = plt.subplots(figsize=(11, 8))
ax.barh(top_journals.index, top_journals.values, color="#7696B2", edgecolor="white", linewidth=0.6)
ax.set_title("Top 20 Journals / Sources by Number of Records")
ax.set_xlabel("Number of records")
ax.set_ylabel("Journal / source")
annotate_barh(ax, top_journals.values)
save_and_show(fig, "07_top_journals.png")

# Cell 19 — Plot Top Countries from Author Affiliations

top_countries = country_counts.head(20).sort_values()

fig, ax = plt.subplots(figsize=(10, 7))
ax.barh(top_countries.index, top_countries.values, color=PASTEL_PALETTE[1], edgecolor="white", linewidth=0.6)
ax.set_title("Top 20 Countries Mentioned in Author Affiliations")
ax.set_xlabel("Country mentions across records")
ax.set_ylabel("Country")
annotate_barh(ax, top_countries.values)
save_and_show(fig, "08_top_countries.png")

# Cell 20 — Plot Top Subject Areas

top_subjects = subject_counts.head(20).sort_values()

fig, ax = plt.subplots(figsize=(11, 8))
ax.barh(top_subjects.index, top_subjects.values, color=PASTEL_PALETTE[5], edgecolor="white", linewidth=0.6)
ax.set_title("Top 20 Subject Areas in Retraction Watch Records")
ax.set_xlabel("Subject mentions across records")
ax.set_ylabel("Subject")
annotate_barh(ax, top_subjects.values)
save_and_show(fig, "09_top_subjects.png")

# Cell 21 — Plot Top Retraction / Update Reasons

top_reasons = reason_counts.head(25).sort_values()

fig, ax = plt.subplots(figsize=(12, 9))
ax.barh(top_reasons.index, top_reasons.values, color=PASTEL_PALETTE[3], edgecolor="white", linewidth=0.6)
ax.set_title("Top 25 Reasons Recorded by Retraction Watch")
ax.set_xlabel("Reason mentions across records")
ax.set_ylabel("Reason")
annotate_barh(ax, top_reasons.values)
save_and_show(fig, "10_top_reasons.png")

# Cell 22 — Plot Top Article Types

top_article_types = article_type_counts.head(15).sort_values()

fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(top_article_types.index, top_article_types.values, color=PASTEL_PALETTE[7], edgecolor="white", linewidth=0.6)
ax.set_title("Top 15 Article Types")
ax.set_xlabel("Article-type mentions")
ax.set_ylabel("Article type")
annotate_barh(ax, top_article_types.values)
save_and_show(fig, "11_top_article_types.png")

# Cell 23 — Plot Paywall Status

paywall_counts = df["Paywalled"].fillna("Unknown").value_counts().sort_values()

fig, ax = plt.subplots(figsize=(8, 5))
ax.barh(paywall_counts.index, paywall_counts.values, color=[PASTEL_PALETTE[i % len(PASTEL_PALETTE)] for i in range(len(paywall_counts))], edgecolor="white", linewidth=0.6)
ax.set_title("Access Status of Retraction / Update Notices")
ax.set_xlabel("Number of records")
ax.set_ylabel("Paywalled?")
annotate_barh(ax, paywall_counts.values)
save_and_show(fig, "12_paywall_status.png")

# Cell 24 — Plot Publication-to-Notice Lag Distribution

lag = df["LagYears"].dropna()
upper = lag.quantile(0.99)

fig, ax = plt.subplots(figsize=(10, 5))
ax.hist(lag.clip(upper=upper), bins=50, color=PASTEL_PALETTE[0], edgecolor="white", linewidth=0.5, alpha=0.96)
ax.axvline(lag.median(), linestyle="--", label=f"Median = {lag.median():.2f} years")
ax.set_title("Publication-to-Notice Lag (Clipped at 99th Percentile)")
ax.set_xlabel("Years between original publication and notice")
ax.set_ylabel("Number of records")
ax.legend()
save_and_show(fig, "13_lag_distribution.png")

# Cell 25 — Plot Lag by Notice Nature

nature_order = df["RetractionNature"].dropna().value_counts().index.tolist()
lag_groups = [
    df.loc[df["RetractionNature"].eq(nature), "LagYears"].dropna().clip(upper=df["LagYears"].quantile(0.99))
    for nature in nature_order
]

fig, ax = plt.subplots(figsize=(10, 6))
bp = ax.boxplot(lag_groups, showfliers=False, patch_artist=True)
for patch, c in zip(bp["boxes"], PASTEL_PALETTE):
    patch.set_facecolor(c); patch.set_alpha(0.9)
for med in bp["medians"]: med.set_color("#274C77"); med.set_linewidth(1.7)
ax.set_xticks(range(1, len(nature_order) + 1))
ax.set_xticklabels(nature_order)
ax.set_title("Publication-to-Notice Lag by Notice Nature")
ax.set_xlabel("Notice nature")
ax.set_ylabel("Lag (years; values above global 99th percentile clipped)")
ax.tick_params(axis="x", rotation=20)
save_and_show(fig, "14_lag_by_notice_nature.png")

# Cell 26 — Plot Median Lag by Original Publication Year

lag_by_original_year = (
    df.dropna(subset=["OriginalYear", "LagYears"])
      .query("OriginalYear >= 1990")
      .groupby("OriginalYear")["LagYears"]
      .median()
)

fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(lag_by_original_year.index.astype(int), lag_by_original_year.values, marker="o", markersize=4, linewidth=2.0, color=PASTEL_PALETTE[1])
ax.set_title("Median Publication-to-Notice Lag by Original Publication Year")
ax.set_xlabel("Original publication year")
ax.set_ylabel("Median lag (years)")
ax.grid(axis="y", alpha=0.25)
save_and_show(fig, "15_median_lag_by_original_year.png")

# Cell 27 — Analyze and Plot Common Reason Pairs

pair_counter = Counter()

for value in df["Reason"].dropna():
    reasons = sorted(set(x.strip() for x in str(value).split(";") if x.strip()))
    for pair in combinations(reasons, 2):
        pair_counter[pair] += 1

top_pairs = pd.DataFrame(
    [(a, b, count) for (a, b), count in pair_counter.most_common(20)],
    columns=["Reason 1", "Reason 2", "Count"]
)
top_pairs["Pair"] = top_pairs["Reason 1"] + " + " + top_pairs["Reason 2"]

display(top_pairs[["Reason 1", "Reason 2", "Count"]])

plot_pairs = top_pairs.sort_values("Count")
fig, ax = plt.subplots(figsize=(12, 9))
ax.barh(plot_pairs["Pair"], plot_pairs["Count"], color=PASTEL_PALETTE[2], edgecolor="white", linewidth=0.6)
ax.set_title("Top 20 Co-occurring Reason Pairs")
ax.set_xlabel("Number of records containing both reasons")
ax.set_ylabel("Reason pair")
annotate_barh(ax, plot_pairs["Count"].values)
save_and_show(fig, "16_top_reason_pairs.png")

# Cell 28 — Plot Reason Co-occurrence Heatmap

top_reason_names = reason_counts.head(12).index.tolist()
matrix = pd.DataFrame(0, index=top_reason_names, columns=top_reason_names, dtype=int)

for value in df["Reason"].dropna():
    items = set(x.strip() for x in str(value).split(";") if x.strip())
    selected = [x for x in top_reason_names if x in items]
    for a in selected:
        matrix.loc[a, a] += 1
    for a, b in combinations(selected, 2):
        matrix.loc[a, b] += 1
        matrix.loc[b, a] += 1

fig, ax = plt.subplots(figsize=(11, 9))
im = ax.imshow(matrix.values, aspect="auto", cmap=PASTEL_BLUE_CMAP)
ax.set_xticks(range(len(matrix.columns)))
ax.set_xticklabels(matrix.columns, rotation=90, fontsize=8)
ax.set_yticks(range(len(matrix.index)))
ax.set_yticklabels(matrix.index, fontsize=8)
ax.set_title("Co-occurrence Matrix for the 12 Most Common Reasons")
fig.colorbar(im, ax=ax, label="Co-occurrence count")
save_and_show(fig, "17_reason_cooccurrence_heatmap.png")

# Cell 29 — Plot Notice-Nature Mix for Top Publishers

top_pub_names = df["Publisher"].value_counts().head(12).index
pub_nature = (
    df[df["Publisher"].isin(top_pub_names)]
    .groupby(["Publisher", "RetractionNature"])
    .size()
    .unstack(fill_value=0)
)
pub_share = pub_nature.div(pub_nature.sum(axis=1), axis=0) * 100
pub_share = pub_share.loc[pub_nature.sum(axis=1).sort_values().index]

fig, ax = plt.subplots(figsize=(11, 8))
left = np.zeros(len(pub_share))
for col in pub_share.columns:
    ax.barh(pub_share.index, pub_share[col].values, left=left, label=col)
    left += pub_share[col].values

ax.set_title("Notice-Nature Composition for Top 12 Publishers")
ax.set_xlabel("Share of publisher records (%)")
ax.set_ylabel("Publisher")
ax.legend(loc="lower right")
save_and_show(fig, "18_publisher_notice_mix.png")

# Cell 30 — Plot How Common Reasons Change Across Time Periods

reason_period_rows = []
for _, row in df[["Reason", "RetractionPeriod"]].dropna().iterrows():
    for reason in [x.strip() for x in str(row["Reason"]).split(";") if x.strip()]:
        reason_period_rows.append((str(row["RetractionPeriod"]), reason))

reason_period = pd.DataFrame(reason_period_rows, columns=["Period", "Reason"])
top_reason_names_8 = reason_counts.head(8).index.tolist()

reason_period_top = (
    reason_period[reason_period["Reason"].isin(top_reason_names_8)]
    .groupby(["Period", "Reason"])
    .size()
    .unstack(fill_value=0)
)

period_order = ["≤2009", "2010–2014", "2015–2019", "2020–2024", "2025+"]
reason_period_top = reason_period_top.reindex(period_order).fillna(0)
reason_period_share = reason_period_top.div(reason_period_top.sum(axis=1), axis=0) * 100

fig, ax = plt.subplots(figsize=(12, 7))
bottom = np.zeros(len(reason_period_share))
x = np.arange(len(reason_period_share))
for col in reason_period_share.columns:
    ax.bar(x, reason_period_share[col].values, bottom=bottom, label=col)
    bottom += reason_period_share[col].values

ax.set_xticks(x)
ax.set_xticklabels(reason_period_share.index)
ax.set_title("Composition of the 8 Most Common Reasons Across Time Periods")
ax.set_xlabel("Retraction/update period")
ax.set_ylabel("Share within these top reasons (%)")
ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left")
save_and_show(fig, "19_reason_mix_over_time.png")

# Cell 31 — Plot DOI and URL Availability

coverage = pd.Series({
    "Original paper DOI": df["HasOriginalDOI"].mean() * 100,
    "Retraction/update DOI": df["HasRetractionDOI"].mean() * 100,
    "Retraction Watch URL": df["HasURL"].mean() * 100,
}).sort_values()

fig, ax = plt.subplots(figsize=(8, 5))
ax.barh(coverage.index, coverage.values, color=PASTEL_PALETTE[1], edgecolor="white", linewidth=0.6)
ax.set_title("Identifier and URL Coverage")
ax.set_xlabel("Records with field available (%)")
ax.set_xlim(0, 100)
for i, v in enumerate(coverage.values):
    ax.text(v, i, f" {v:.1f}%", va="center")
save_and_show(fig, "20_identifier_coverage.png")

# Cell 32 — Plot Author Count Distribution

author_counts = df.loc[df["AuthorCount"] > 0, "AuthorCount"]
upper_authors = max(1, int(author_counts.quantile(0.99)))

fig, ax = plt.subplots(figsize=(10, 5))
ax.hist(author_counts.clip(upper=upper_authors), bins=range(1, upper_authors + 2), color=PASTEL_PALETTE[5], edgecolor="white", linewidth=0.5)
ax.set_title("Number of Authors per Record (Clipped at 99th Percentile)")
ax.set_xlabel("Author count")
ax.set_ylabel("Number of records")
save_and_show(fig, "21_author_count_distribution.png")

# Cell 33 — Plot Numeric Feature Correlations

numeric_cols = ["LagYears", "AuthorCount", "CountryCount", "SubjectCount", "ReasonCount", "ArticleTypeCount"]
corr = df[numeric_cols].corr(method="spearman")

fig, ax = plt.subplots(figsize=(8, 7))
im = ax.imshow(corr.values, vmin=-1, vmax=1, aspect="auto", cmap=PASTEL_DIVERGING)
ax.set_xticks(range(len(corr.columns)))
ax.set_xticklabels(corr.columns, rotation=45, ha="right")
ax.set_yticks(range(len(corr.index)))
ax.set_yticklabels(corr.index)
ax.set_title("Spearman Correlation of Engineered Numeric Features")
fig.colorbar(im, ax=ax, label="Spearman correlation")

for i in range(len(corr.index)):
    for j in range(len(corr.columns)):
        ax.text(j, i, f"{corr.iloc[i, j]:.2f}", ha="center", va="center", fontsize=8)

save_and_show(fig, "22_numeric_feature_correlation.png")

# Cell 34 — Plot Single-Country vs Multi-Country Records

collab_counts = df["InternationalCollaboration"].value_counts().sort_values()

fig, ax = plt.subplots(figsize=(8, 5))
ax.barh(collab_counts.index, collab_counts.values, color=PASTEL_PALETTE[7], edgecolor="white", linewidth=0.6)
ax.set_title("Single-Country vs Multi-Country Affiliation Records")
ax.set_xlabel("Number of records")
ax.set_ylabel("Affiliation scope")
annotate_barh(ax, collab_counts.values)
save_and_show(fig, "23_collaboration_scope.png")

# Cell 35 — Plot Lag by Collaboration Scope

collab_order = ["Single/unknown country", "Multiple countries"]
collab_lag = [
    df.loc[df["InternationalCollaboration"].eq(label), "LagYears"].dropna().clip(upper=df["LagYears"].quantile(0.99))
    for label in collab_order
]

fig, ax = plt.subplots(figsize=(8, 6))
bp = ax.boxplot(collab_lag, showfliers=False, patch_artist=True)
for patch, c in zip(bp["boxes"], [PASTEL_PALETTE[7], PASTEL_PALETTE[1]]):
    patch.set_facecolor(c); patch.set_alpha(0.9)
for med in bp["medians"]: med.set_color("#274C77"); med.set_linewidth(1.7)
ax.set_xticks([1, 2])
ax.set_xticklabels(collab_order)
ax.set_title("Publication-to-Notice Lag by Collaboration Scope")
ax.set_xlabel("Affiliation scope")
ax.set_ylabel("Lag (years; values above global 99th percentile clipped)")
ax.tick_params(axis="x", rotation=15)
save_and_show(fig, "24_lag_by_collaboration_scope.png")

"""# Part II — Advanced Statistical and Critical Analysis

The cells below extend the standard EDA into analyses that test whether headline patterns remain meaningful after accounting for skewness, multi-label structure, incomplete years, grouped notice events, and database architecture. The emphasis is on **effect size and robustness**, not only p-values.
"""

# Cell 36 — Advanced Helper Functions

def split_unique(value):
    if pd.isna(value):
        return []
    return sorted(set(x.strip() for x in str(value).split(";") if x.strip()))


def normalize_doi(value):
    if pd.isna(value):
        return pd.NA
    s = str(value).strip().lower()
    s = re.sub(r"^https?://(dx\.)?doi\.org/", "", s)
    s = re.sub(r"^doi:\s*", "", s)
    return s if s else pd.NA


def bh_fdr(p_values):
    p = np.asarray(p_values, dtype=float)
    n = len(p)
    if n == 0:
        return np.array([])
    order = np.argsort(p)
    ranked = p[order]
    adj = ranked * n / np.arange(1, n + 1)
    adj = np.minimum.accumulate(adj[::-1])[::-1]
    adj = np.clip(adj, 0, 1)
    out = np.empty(n)
    out[order] = adj
    return out


def rank_biserial_from_u(u_stat, n1, n2):
    # Positive values mean the first group tends to have larger values.
    return 2 * u_stat / (n1 * n2) - 1


def gini(values):
    x = np.asarray(values, dtype=float)
    x = x[np.isfinite(x) & (x >= 0)]
    if len(x) == 0 or x.sum() == 0:
        return np.nan
    x = np.sort(x)
    n = len(x)
    return (2 * np.sum((np.arange(1, n + 1)) * x) / (n * x.sum())) - (n + 1) / n


def two_prop_stats(x_old, n_old, x_new, n_new):
    p_old = x_old / n_old if n_old else np.nan
    p_new = x_new / n_new if n_new else np.nan
    pooled = (x_old + x_new) / (n_old + n_new)
    se = math.sqrt(max(pooled * (1 - pooled) * (1 / n_old + 1 / n_new), 0)) if n_old and n_new else np.nan
    z = (p_new - p_old) / se if se and np.isfinite(se) and se > 0 else np.nan
    pval = 2 * norm.sf(abs(z)) if np.isfinite(z) else np.nan
    rr = p_new / p_old if p_old and p_old > 0 else np.nan
    if x_old > 0 and x_new > 0 and np.isfinite(rr):
        se_log_rr = math.sqrt((1/x_new) - (1/n_new) + (1/x_old) - (1/n_old))
        lo = math.exp(math.log(rr) - 1.96 * se_log_rr)
        hi = math.exp(math.log(rr) + 1.96 * se_log_rr)
    else:
        lo = hi = np.nan
    return p_old, p_new, pval, rr, lo, hi

# Primary inferential population: formal retractions only.
ret = df[df["RetractionNature"].eq("Retraction")].copy()
ret["RetractionDOI_norm"] = ret["RetractionDOI"].apply(normalize_doi)
ret["OriginalPaperDOI_norm"] = ret["OriginalPaperDOI"].apply(normalize_doi)
ret["RetractionDay"] = ret["RetractionDate"].dt.normalize()

print(f"Primary retraction population: {len(ret):,} records ({len(ret)/len(df):.2%} of cleaned records)")

"""## 1. Reproducibility and semantic missingness"""

# Cell 37 — Dataset Provenance and Fingerprint

source_label = str(source_path) if source_path is not None else GITLAB_RAW_URL
sha256_value = "Not available for URL-loaded data"
if source_path is not None and Path(source_path).exists():
    h = hashlib.sha256()
    with open(source_path, "rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(block)
    sha256_value = h.hexdigest()

provenance = pd.DataFrame({
    "Item": ["Source", "Raw rows", "Clean rows", "Primary retractions", "Latest notice date", "SHA-256"],
    "Value": [source_label, f"{len(raw_df):,}", f"{len(df):,}", f"{len(ret):,}",
              str(df["RetractionDate"].max().date()), sha256_value]
})
display(provenance)

# Cell 38 — Raw NaN vs Effective Missingness

raw_nonblank = raw_df.dropna(how="all").copy()
fields = ["OriginalPaperDOI", "RetractionDOI", "OriginalPaperPubMedID", "RetractionPubMedID", "URLS", "Notes"]
rows = []
for col in fields:
    raw_missing = raw_nonblank[col].isna().mean() * 100
    effective_missing = df[col].isna().mean() * 100
    rows.append((col, raw_missing, effective_missing))
semantic_missing = pd.DataFrame(rows, columns=["Variable", "Raw NaN %", "Effective missing %"]).sort_values("Effective missing %")
display(semantic_missing)

fig, ax = plt.subplots(figsize=(10, 6))
y = np.arange(len(semantic_missing))
ax.barh(y - 0.18, semantic_missing["Raw NaN %"], height=0.36, label="Raw NaN", color=PASTEL_PALETTE[7])
ax.barh(y + 0.18, semantic_missing["Effective missing %"], height=0.36, label="Effective missing", color=PASTEL_PALETTE[3])
ax.set_yticks(y)
ax.set_yticklabels(semantic_missing["Variable"])
ax.set_xlabel("Missing / unavailable records (%)")
ax.set_title("Raw NaN vs Effective Missingness")
ax.legend()
save_and_show(fig, "25_semantic_missingness.png")

"""## 2. Identifier multiplicity and notice lifecycle structure"""

# Cell 39 — Identifier Multiplicity Audit

def repeated_group_summary(series):
    vc = series.dropna().value_counts()
    rep = vc[vc > 1]
    return len(rep), int(rep.sum())

title_norm = ret["Title"].astype("string").str.lower().str.replace(r"\s+", " ", regex=True).str.strip()
summary_rows = []
for name, series in [
    ("Normalized title", title_norm),
    ("Original-paper DOI", ret["OriginalPaperDOI_norm"]),
    ("Retraction-notice DOI", ret["RetractionDOI_norm"]),
]:
    groups, records = repeated_group_summary(series)
    summary_rows.append((name, groups, records))

identifier_summary = pd.DataFrame(summary_rows, columns=["Identifier", "Repeated groups", "Records in repeated groups"])
print(f"Duplicate Record IDs remaining: {ret['Record ID'].duplicated().sum():,}")
display(identifier_summary)

# Cell 40 — Observed DOI-Linked Notice Lifecycles

lifecycle_df = df.copy()
lifecycle_df["OriginalPaperDOI_norm"] = lifecycle_df["OriginalPaperDOI"].apply(normalize_doi)
linked = lifecycle_df.dropna(subset=["OriginalPaperDOI_norm"]).copy()

combo_counts = (
    linked.groupby("OriginalPaperDOI_norm")["RetractionNature"]
    .agg(lambda s: " + ".join(sorted(set(s.dropna().astype(str)))))
    .value_counts()
)
print("Most common observed notice combinations linked to the same original DOI:")
display(combo_counts.head(10).rename("DOI groups").to_frame())

# Time from earliest EOC to earliest retraction in DOI groups containing both.
def lifecycle_interval(group, first_type, second_type):
    a = group.loc[group["RetractionNature"].eq(first_type), "RetractionDate"].dropna()
    b = group.loc[group["RetractionNature"].eq(second_type), "RetractionDate"].dropna()
    if len(a) and len(b):
        d = (b.min() - a.min()).days
        return d if d >= 0 else np.nan
    return np.nan

eoc_to_ret = linked.groupby("OriginalPaperDOI_norm").apply(
    lambda g: lifecycle_interval(g, "Expression of concern", "Retraction"), include_groups=False
).dropna()
if len(eoc_to_ret):
    print(f"Observed EOC→Retraction groups: {len(eoc_to_ret):,}; median interval = {eoc_to_ret.median():.0f} days")

"""## 3. Retraction timing distribution and complexity"""

# Cell 41 — ECDF of Publication-to-Retraction Lag
lag = ret["LagYears"].dropna()
q = lag.quantile([0.25, 0.50, 0.75, 0.90, 0.95, 0.99])
display(q.rename("Lag years").to_frame())

x = np.sort(lag.values)
y = np.arange(1, len(x) + 1) / len(x)
upper = np.quantile(x, 0.99)
mask = x <= upper
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(x[mask], 100*y[mask], linewidth=2.4, color=PASTEL_PALETTE[0])
for val, label in [(q.loc[0.50], "50%"), (q.loc[0.75], "75%"), (q.loc[0.90], "90%")]:
    ax.axvline(val, linestyle="--", linewidth=1)
    ax.text(val, 5, f"{label}: {val:.2f} y", rotation=90, va="bottom")
ax.set_xlabel("Years from original publication to retraction")
ax.set_ylabel("Cumulative percentage of retractions")
ax.set_title("Empirical Cumulative Distribution of Retraction Lag")
ax.set_ylim(0, 100)
save_and_show(fig, "26_lag_ecdf.png")

# Cell 42 — Complexity–Lag Spearman Associations
complexity_cols = ["AuthorCount", "CountryCount", "SubjectCount", "ReasonCount", "ArticleTypeCount"]
rows=[]
for col in complexity_cols:
    tmp = ret[[col, "LagYears"]].dropna()
    rho, pval = stats.spearmanr(tmp[col], tmp["LagYears"])
    rows.append((col, len(tmp), rho, pval))
complexity_assoc = pd.DataFrame(rows, columns=["Feature", "N", "Spearman rho", "p-value"])
complexity_assoc["FDR q"] = bh_fdr(complexity_assoc["p-value"].values)
display(complexity_assoc.sort_values("Spearman rho", ascending=False))

"""## 4. Effect sizes for article types, reasons, and collaboration"""

# Cell 43 — Article-Type Lag Effect Sizes
article_lists = ret["ArticleType"].apply(split_unique)
article_counts = Counter(x for xs in article_lists for x in xs)
article_labels = [k for k,v in article_counts.most_common(12) if v >= 300]
rows=[]
for label in article_labels:
    mask = article_lists.apply(lambda xs, lab=label: lab in xs)
    a = ret.loc[mask, "LagDays"].dropna()
    b = ret.loc[~mask, "LagDays"].dropna()
    if len(a) >= 20 and len(b) >= 20:
        u,p = stats.mannwhitneyu(a,b,alternative="two-sided")
        rbc = rank_biserial_from_u(u,len(a),len(b))
        rows.append((label,len(a),a.median()-b.median(),rbc,p))
article_lag = pd.DataFrame(rows, columns=["Article type","N with type","Median difference (days)","Rank-biserial","p-value"])
article_lag["FDR q"] = bh_fdr(article_lag["p-value"].values)
display(article_lag.reindex(article_lag["Rank-biserial"].abs().sort_values(ascending=False).index))

# Cell 44 — Major Reason Lag Effect Sizes
reason_lists = ret["Reason"].apply(split_unique)
reason_counts_ret = Counter(x for xs in reason_lists for x in xs)
reason_labels = [k for k,v in reason_counts_ret.most_common(18) if v >= 800]
rows=[]
for label in reason_labels:
    mask = reason_lists.apply(lambda xs, lab=label: lab in xs)
    a = ret.loc[mask, "LagDays"].dropna()
    b = ret.loc[~mask, "LagDays"].dropna()
    if len(a) >= 20 and len(b) >= 20:
        u,p = stats.mannwhitneyu(a,b,alternative="two-sided")
        rbc = rank_biserial_from_u(u,len(a),len(b))
        rows.append((label,len(a),a.median()-b.median(),rbc,p))
reason_lag = pd.DataFrame(rows, columns=["Reason","N with reason","Median difference (days)","Rank-biserial","p-value"])
reason_lag["FDR q"] = bh_fdr(reason_lag["p-value"].values)
reason_lag = reason_lag.reindex(reason_lag["Rank-biserial"].abs().sort_values(ascending=False).index)
display(reason_lag)

plot_df = reason_lag.head(12).sort_values("Rank-biserial")
fig, ax = plt.subplots(figsize=(10, 7))
ax.scatter(plot_df["Rank-biserial"], plot_df["Reason"], s=80, color=PASTEL_PALETTE[2], edgecolor="white", linewidth=0.6)
ax.axvline(0, linewidth=1)
ax.set_xlabel("Rank-biserial effect size (positive = longer lag)")
ax.set_title("Retraction Reasons Associated with Longer or Shorter Lag")
save_and_show(fig, "27_reason_lag_effects.png")

# Cell 45 — Multi-Country vs Other Retraction Lag
multi_mask = ret["CountryCount"].gt(1)
a = ret.loc[multi_mask, "LagDays"].dropna()
b = ret.loc[~multi_mask, "LagDays"].dropna()
u,p = stats.mannwhitneyu(a,b,alternative="two-sided")
rbc = rank_biserial_from_u(u,len(a),len(b))
collab_test = pd.DataFrame({
    "Measure": ["Multi-country records", "Other records", "Median lag multi-country", "Median lag other", "Rank-biserial", "p-value"],
    "Value": [f"{multi_mask.sum():,}", f"{(~multi_mask).sum():,}", f"{a.median():.0f} days", f"{b.median():.0f} days", f"{rbc:.3f}", f"{p:.3g}"]
})
display(collab_test)

"""## 5. Recent shifts in retraction reasons"""

# Cell 46 — Reason Prevalence Shift: 2019–2022 vs 2023–2025
old = ret[ret["RetractionYear"].between(2019, 2022)].copy()
new = ret[ret["RetractionYear"].between(2023, 2025)].copy()
old_lists = old["Reason"].apply(split_unique)
new_lists = new["Reason"].apply(split_unique)
all_reason_counts = Counter(x for xs in pd.concat([old_lists,new_lists]) for x in xs)
labels = [k for k,v in all_reason_counts.most_common(35) if v >= 500]
rows=[]
for label in labels:
    x1 = int(old_lists.apply(lambda xs, lab=label: lab in xs).sum())
    x2 = int(new_lists.apply(lambda xs, lab=label: lab in xs).sum())
    p1,p2,pval,rr,lo,hi = two_prop_stats(x1,len(old),x2,len(new))
    rows.append((label,x1,x2,100*p1,100*p2,100*(p2-p1),rr,lo,hi,pval))
reason_shift = pd.DataFrame(rows, columns=["Reason","2019-22 count","2023-25 count","2019-22 %","2023-25 %","Change (pp)","Risk ratio","RR 95% low","RR 95% high","p-value"])
reason_shift["FDR q"] = bh_fdr(reason_shift["p-value"].fillna(1).values)
reason_shift = reason_shift.reindex(reason_shift["Change (pp)"].abs().sort_values(ascending=False).index)
display(reason_shift.head(20))

plot_df = reason_shift.head(15).sort_values("Change (pp)")
fig, ax = plt.subplots(figsize=(11, 8))
ax.barh(plot_df["Reason"], plot_df["Change (pp)"], color=PASTEL_PALETTE[3], edgecolor="white", linewidth=0.5)
ax.axvline(0, linewidth=1)
ax.set_xlabel("Change in prevalence (percentage points)")
ax.set_title("Largest Retraction-Reason Shifts: 2019–2022 vs 2023–2025")
save_and_show(fig, "28_reason_shift_pp.png")

"""## 6. Reason co-occurrence, association strength, and network structure"""

# Cell 46 — Reason Pair Support, Jaccard, and Lift
single = Counter()
pairs = Counter()
for xs in reason_lists:
    xs = sorted(set(xs))
    single.update(xs)
    pairs.update(combinations(xs,2))
N = len(ret)
rows=[]
for (a,b), c in pairs.items():
    if c < 250:
        continue
    support = c/N
    jaccard = c/(single[a]+single[b]-c)
    lift = support / ((single[a]/N)*(single[b]/N))
    conf_ab = c/single[a]
    conf_ba = c/single[b]
    rows.append((a,b,c,support,jaccard,lift,conf_ab,conf_ba))
pair_stats = pd.DataFrame(rows, columns=["Reason A","Reason B","Co-occurrence","Support","Jaccard","Lift","Confidence A→B","Confidence B→A"])
pair_stats = pair_stats.sort_values(["Lift","Co-occurrence"], ascending=False)
display(pair_stats.head(20))

# Cell 48 — Reason Association Network
net_edges = pair_stats[(pair_stats["Co-occurrence"] >= 500) & (pair_stats["Lift"] >= 1.5)].head(35)
G = nx.Graph()
for _,r in net_edges.iterrows():
    G.add_edge(r["Reason A"], r["Reason B"], weight=float(r["Lift"]), count=int(r["Co-occurrence"]))

fig, ax = plt.subplots(figsize=(13, 10))
if G.number_of_nodes():
    pos = nx.spring_layout(G, seed=42, weight="weight")
    sizes = [250 + 20*math.sqrt(single[n]) for n in G.nodes()]
    widths = [0.5 + 0.25*G[u][v]["weight"] for u,v in G.edges()]
    nx.draw_networkx_nodes(G,pos,node_size=sizes,ax=ax,alpha=0.85)
    nx.draw_networkx_edges(G,pos,width=widths,ax=ax,alpha=0.35)
    nx.draw_networkx_labels(G,pos,font_size=7,ax=ax)
ax.set_title("Network of Strong Retraction-Reason Associations")
ax.axis("off")
save_and_show(fig, "29_reason_network.png")

"""## 7. Subject–reason enrichment"""

# Cell 49 — Subject–Reason Fisher Enrichment
subject_lists_ret = ret["Subject"].apply(lambda v: [clean_subject_label(x) for x in split_unique(v)])
subject_counts_ret = Counter(x for xs in subject_lists_ret for x in xs)
top_subjects = [k for k,v in subject_counts_ret.most_common(8) if v >= 1000]
top_reasons = [k for k,v in reason_counts_ret.most_common(10) if v >= 1000]

subject_masks = {s: subject_lists_ret.apply(lambda xs, s=s: s in xs).values for s in top_subjects}
reason_masks = {r: reason_lists.apply(lambda xs, r=r: r in xs).values for r in top_reasons}
rows=[]
for s in top_subjects:
    sm = subject_masks[s]
    for r in top_reasons:
        rm = reason_masks[r]
        a = int((sm & rm).sum())
        b = int((sm & ~rm).sum())
        c = int((~sm & rm).sum())
        d = int((~sm & ~rm).sum())
        odds,p = fisher_exact([[a,b],[c,d]])
        rows.append((s,r,a,odds,p))
enrich = pd.DataFrame(rows, columns=["Subject","Reason","Joint records","Odds ratio","p-value"])
enrich["FDR q"] = bh_fdr(enrich["p-value"].values)
display(enrich.sort_values("Odds ratio", ascending=False).head(20))

# Bubble matrix: x=reason, y=subject, size=joint count, marker position fixed; log2 OR shown by annotation sign/magnitude.
fig, ax = plt.subplots(figsize=(14, 8))
for yi,s in enumerate(top_subjects):
    for xi,r in enumerate(top_reasons):
        row = enrich[(enrich.Subject==s)&(enrich.Reason==r)].iloc[0]
        orv = max(float(row["Odds ratio"]), 1e-6)
        size = 20 + 2.0*math.sqrt(max(int(row["Joint records"]),0))
        ax.scatter(xi, yi, s=size, color=PASTEL_PALETTE[(xi + yi) % len(PASTEL_PALETTE)], alpha=0.90, edgecolor="white", linewidth=0.4)
        ax.text(xi, yi, f"{math.log2(orv):.1f}", ha="center", va="center", fontsize=6)
ax.set_xticks(range(len(top_reasons)))
ax.set_xticklabels(top_reasons, rotation=60, ha="right", fontsize=7)
ax.set_yticks(range(len(top_subjects)))
ax.set_yticklabels(top_subjects, fontsize=8)
ax.set_title("Subject–Reason Enrichment (labels show log2 odds ratio)")
ax.set_xlabel("Retraction reason")
ax.set_ylabel("Subject")
save_and_show(fig, "30_subject_reason_enrichment.png")

"""## 8. Publisher concentration and grouped-notice sensitivity"""

# Cell 50 — Publisher Concentration by Year
complete = ret[ret["RetractionYear"].between(2000, 2025)].dropna(subset=["Publisher","RetractionYear"]).copy()
rows=[]
for year,g in complete.groupby("RetractionYear"):
    counts = g["Publisher"].value_counts().values.astype(float)
    shares = counts/counts.sum()
    rows.append((int(year), len(g), float((shares**2).sum()), gini(counts), float(shares[0]), float(shares[:5].sum())))
concentration = pd.DataFrame(rows, columns=["Year","N","HHI","Gini","Top-1 share","Top-5 share"])
display(concentration.sort_values("HHI", ascending=False).head(12))

fig, ax = plt.subplots(figsize=(11, 5))
ax.plot(concentration["Year"], concentration["HHI"], marker="o", linewidth=2.0, label="Publisher HHI", color=PASTEL_PALETTE[0])
ax.plot(concentration["Year"], concentration["Top-1 share"], marker="o", linewidth=2.0, label="Top publisher share", color=PASTEL_PALETTE[4])
ax.set_xlabel("Retraction year")
ax.set_ylabel("Concentration")
ax.set_title("Publisher Concentration Over Time")
ax.legend()
save_and_show(fig, "31_publisher_concentration.png")

# Cell 51 — Candidate Grouped-Notice Events and Threshold Sensitivity
# Transparent proxy: same publisher + same retraction date. This identifies grouped notices, not misconduct.
base_group_sizes = ret.groupby(["Publisher","RetractionDay"]).size().rename("group_size")
thresholds = [10,25,50,100]
rows=[]
for t in thresholds:
    big = base_group_sizes[base_group_sizes >= t]
    records = int(big.sum())
    rows.append((t,len(big),records,records/len(ret)))
batch_sensitivity = pd.DataFrame(rows, columns=["Threshold","Candidate groups","Records in groups","Share of retractions"])
display(batch_sensitivity)

BATCH_THRESHOLD = 25
batch_keys = set(base_group_sizes[base_group_sizes >= BATCH_THRESHOLD].index)
ret["CandidateBatch"] = [
    (pub, day) in batch_keys for pub,day in zip(ret["Publisher"],ret["RetractionDay"])
]
print(f"Candidate grouped-notice records at ≥{BATCH_THRESHOLD}: {ret['CandidateBatch'].sum():,} ({ret['CandidateBatch'].mean():.2%})")

# Cell 52 — Shared Retraction DOI Validation of Grouped-Notice Proxy
shared_doi_sizes = ret.dropna(subset=["RetractionDOI_norm"]).groupby("RetractionDOI_norm").size()
large_shared = set(shared_doi_sizes[shared_doi_sizes >= BATCH_THRESHOLD].index)
shared_mask = ret["RetractionDOI_norm"].isin(large_shared)
overlap = int((shared_mask & ret["CandidateBatch"]).sum())
validation = pd.DataFrame({
    "Measure": ["Shared RetractionDOI groups", "Records in shared DOI groups", "Shared-DOI records also candidate batch"],
    "Value": [f"{len(large_shared):,}", f"{shared_mask.sum():,}", f"{overlap:,} / {shared_mask.sum():,} ({overlap/shared_mask.sum():.2%})" if shared_mask.sum() else "n/a"]
})
display(validation)

# Cell 57 — Annual Batch vs Non-Batch Decomposition
annual_batch = ret[ret["RetractionYear"].between(2000,2025)].groupby(["RetractionYear","CandidateBatch"]).size().unstack(fill_value=0)
annual_batch = annual_batch.rename(columns={False:"Other retractions", True:"Candidate grouped notices"})
for col in ["Other retractions","Candidate grouped notices"]:
    if col not in annual_batch.columns:
        annual_batch[col]=0

display(annual_batch.tail(10))
fig, ax = plt.subplots(figsize=(12,6))
ax.bar(annual_batch.index, annual_batch["Other retractions"], label="Other retractions", color=PASTEL_PALETTE[7])
ax.bar(annual_batch.index, annual_batch["Candidate grouped notices"], bottom=annual_batch["Other retractions"], label=f"Candidate groups (≥{BATCH_THRESHOLD})", color=PASTEL_PALETTE[3])
ax.set_xlabel("Retraction year")
ax.set_ylabel("Number of retractions")
ax.set_title("Annual Retractions Decomposed by Candidate Grouped-Notice Status")
ax.legend()
save_and_show(fig, "32_annual_batch_decomposition.png")

# Cell 53 — Batch vs Other Lag Comparison
batch_lag = ret.loc[ret["CandidateBatch"], "LagDays"].dropna()
other_lag = ret.loc[~ret["CandidateBatch"], "LagDays"].dropna()
if len(batch_lag) and len(other_lag):
    u,p = stats.mannwhitneyu(batch_lag,other_lag,alternative="two-sided")
    rbc = rank_biserial_from_u(u,len(batch_lag),len(other_lag))
    display(pd.DataFrame({
        "Metric":["Candidate-batch median lag","Other median lag","Rank-biserial","p-value"],
        "Value":[f"{batch_lag.median():.0f} days",f"{other_lag.median():.0f} days",f"{rbc:.3f}",f"{p:.3g}"]
    }))

# Cell 54 — Batch-Adjusted Recent Reason Shifts
nonbatch = ret[~ret["CandidateBatch"]].copy()
old_nb = nonbatch[nonbatch["RetractionYear"].between(2019,2022)]
new_nb = nonbatch[nonbatch["RetractionYear"].between(2023,2025)]
old_nb_lists = old_nb["Reason"].apply(split_unique)
new_nb_lists = new_nb["Reason"].apply(split_unique)
nb_rows=[]
for label in reason_shift["Reason"].head(25):
    x1 = int(old_nb_lists.apply(lambda xs, lab=label: lab in xs).sum())
    x2 = int(new_nb_lists.apply(lambda xs, lab=label: lab in xs).sum())
    p1,p2,pval,rr,lo,hi = two_prop_stats(x1,len(old_nb),x2,len(new_nb))
    nb_rows.append((label,100*(p2-p1),pval))
nonbatch_shift = pd.DataFrame(nb_rows, columns=["Reason","Non-batch change (pp)","Non-batch p-value"])
shift_compare = reason_shift[["Reason","Change (pp)"]].merge(nonbatch_shift,on="Reason",how="inner")
display(shift_compare.reindex((shift_compare["Change (pp)"]-shift_compare["Non-batch change (pp)"]).abs().sort_values(ascending=False).index).head(15))

fig, ax = plt.subplots(figsize=(8,8))
ax.scatter(shift_compare["Change (pp)"], shift_compare["Non-batch change (pp)"], color=PASTEL_PALETTE[2], alpha=0.9, edgecolor="white", linewidth=0.5)
lim = max(abs(shift_compare[["Change (pp)","Non-batch change (pp)"]].values).max(),1)
ax.plot([-lim,lim],[-lim,lim],linestyle="--",linewidth=1)
ax.axhline(0,linewidth=0.8); ax.axvline(0,linewidth=0.8)
ax.set_xlabel("All retractions: reason shift (pp)")
ax.set_ylabel("After excluding candidate grouped notices (pp)")
ax.set_title("Sensitivity of Recent Reason Shifts to Grouped Notices")
save_and_show(fig, "33_reason_shift_batch_sensitivity.png")

"""## 9. Transparency and recent database completeness"""

# Cell 55 — Identifier and Paywall Trends by Year
trend = ret[ret["RetractionYear"].between(2000,2025)].copy()
trend["HasOriginalDOI"] = trend["OriginalPaperDOI"].notna()
trend["HasRetractionDOI"] = trend["RetractionDOI"].notna()
trend["IsPaywalled"] = trend["Paywalled"].eq("Yes")
annual_transparency = trend.groupby("RetractionYear").agg(
    Original_DOI=("HasOriginalDOI","mean"),
    Retraction_DOI=("HasRetractionDOI","mean"),
    Paywalled=("IsPaywalled","mean")
).mul(100)
display(annual_transparency.tail(10))

fig, ax = plt.subplots(figsize=(11,5))
ax.plot(annual_transparency.index, annual_transparency["Original_DOI"], label="Original-paper DOI", linewidth=2.1, color=PASTEL_PALETTE[1])
ax.plot(annual_transparency.index, annual_transparency["Retraction_DOI"], label="Retraction DOI", linewidth=2.1, color=PASTEL_PALETTE[2])
ax.set_xlabel("Retraction year")
ax.set_ylabel("Records with DOI (%)")
ax.set_title("Identifier Coverage Over Time")
ax.legend()
save_and_show(fig, "34_identifier_coverage_over_time.png")

# Cell 56 — Report-Ready Analytical Summary
critical_metrics = pd.DataFrame({
    "Metric": [
        "Raw rows", "Clean valid records", "Primary retractions", "Retraction share",
        "Median retraction lag", "90th percentile lag", "Original-paper DOI coverage",
        "Retraction DOI coverage", "Multi-country share", f"Candidate grouped-notice share (≥{BATCH_THRESHOLD})",
        "Latest notice date"
    ],
    "Value": [
        f"{len(raw_df):,}", f"{len(df):,}", f"{len(ret):,}", f"{len(ret)/len(df):.2%}",
        f"{ret['LagYears'].median():.2f} years", f"{ret['LagYears'].quantile(0.90):.2f} years",
        f"{ret['OriginalPaperDOI'].notna().mean():.1%}", f"{ret['RetractionDOI'].notna().mean():.1%}",
        f"{ret['CountryCount'].gt(1).mean():.1%}", f"{ret['CandidateBatch'].mean():.1%}",
        str(df['RetractionDate'].max().date())
    ]
})
display(critical_metrics)

# Cell 57 — Export Main Analytical Tables
TABLE_DIR = OUTPUT_DIR / "tables"
TABLE_DIR.mkdir(parents=True, exist_ok=True)

exports = {
    "semantic_missingness.csv": semantic_missing,
    "identifier_multiplicity.csv": identifier_summary,
    "complexity_lag_associations.csv": complexity_assoc,
    "article_type_lag_effects.csv": article_lag,
    "reason_lag_effects.csv": reason_lag,
    "recent_reason_shifts.csv": reason_shift,
    "reason_pair_statistics.csv": pair_stats,
    "subject_reason_enrichment.csv": enrich,
    "publisher_concentration.csv": concentration,
    "batch_threshold_sensitivity.csv": batch_sensitivity,
    "reason_shift_batch_sensitivity.csv": shift_compare,
    "annual_identifier_coverage.csv": annual_transparency,
    "critical_metrics.csv": critical_metrics,
}
for filename, table in exports.items():
    table.to_csv(TABLE_DIR / filename, index=False)
print(f"Exported {len(exports)} tables to: {TABLE_DIR}")

# Cell 58 — Save Cleaned Dataset
cleaned_path = OUTPUT_DIR / "retraction_watch_cleaned_enhanced.csv"
df.to_csv(cleaned_path, index=False)
print(f"Saved cleaned dataset: {cleaned_path}")

# Cell 59 — Generate a Report-Ready Markdown Summary
summary_text = f"""# Retraction Watch Data Analysis — Enhanced Independent Version

## Executive Summary
The analysis retained {len(df):,} valid records from {len(raw_df):,} raw CSV rows. Formal retractions account for {len(ret)/len(df):.2%} of cleaned records and form the primary inferential population. The median publication-to-retraction lag is {ret['LagYears'].median():.2f} years, while the 90th percentile is {ret['LagYears'].quantile(0.90):.2f} years, confirming a strongly right-skewed timing distribution.

## Preprocessing
Completely empty rows and columns were removed, strings were standardized, identifier placeholders were normalized, PubMed ID value 0 was treated as unavailable, dates were parsed, negative lag values were excluded from timing analysis, duplicate Record IDs were checked, and multi-value fields were parsed without inventing missing identifiers.

## EDA and Critical Analysis
The project examines notice composition, annual trends, publishers, journals, countries, subjects, article types, reasons, publication-to-notice lag, reason co-occurrence, identifier coverage, collaboration structure, effect sizes, recent reason shifts, subject–reason enrichment, publisher concentration, grouped-notice sensitivity, and DOI-linked notice structure.

The key interpretive limitation is the absence of publication-volume denominators. Raw counts therefore describe the Retraction Watch database and must not be presented as misconduct rates. Grouped notice events, evolving reason taxonomies, incomplete recent years, right truncation, and the multi-label nature of the data can all change the interpretation of headline trends.
"""
summary_path = OUTPUT_DIR / "enhanced_analysis_summary.md"
summary_path.write_text(summary_text, encoding="utf-8")
print(summary_text)
print(f"Saved summary: {summary_path}")

#Cell 60 — Create ZIP Archive of Outputs
from pathlib import Path
import shutil

# Create ZIP OUTSIDE the folder being compressed
zip_base = Path("retraction_watch_outputs")

archive = shutil.make_archive(
    str(zip_base),
    "zip",
    root_dir=str(OUTPUT_DIR)
)

print("ZIP created successfully:")
print(Path(archive).resolve())